FROM openjdk:8-jdk-alpine
RUN addgroup -S spring && adduser -S spring -G spring
USER spring:spring
ARG DEPENDENCY=target/dependency
COPY ${DEPENDENCY}/*.jar /app/lib/app.jar

ENTRYPOINT ["java","-cp","app:app/lib/*","-jar ","/app/lib/app.jar]